In [1]:
import numpy as np

# Step 1: Generate a 3x4 random matrix
matrix_3x4 = np.random.randint(1, 21, size=(3, 4))  # Adjust range as needed
A = matrix_3x4[:, :3]  # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3]   # Right-hand side vector (last column)

print("Generated 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)

Generated 3x4 Matrix:
[[ 9 10  3 18]
 [17  8  3 14]
 [16 12 12 13]]

Coefficient Matrix (A):
[[ 9 10  3]
 [17  8  3]
 [16 12 12]]

Right-hand Side Vector (b):
[18 14 13]


In [2]:
# Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_manual = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

# Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Direct Gaussian elimination
print("\nSolution using Gaussian Elimination (NumPy):")
print(x_gaussian)

# Verify the solution
b_check = np.dot(A, x_gaussian)  # Recompute b using A and the computed x
print("\nVerification (Ax = b):")
print(b_check)


Solution using Matrix Inverse Method:
[ 0.02272727  2.09090909 -1.03787879]

Solution using Gaussian Elimination (NumPy):
[ 0.02272727  2.09090909 -1.03787879]

Verification (Ax = b):
[18. 14. 13.]
